services:
  - type: web
    name: growfund-backend
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /api/health/
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
      - key: FRONTEND_URL
        value: https://growfundapp.us
      - key: BACKEND_URL
        sync: false
